In [1]:
import numpy as np
import pandas as pd
import openpyxl

## Prepdata 3

In [2]:
prep_data = openpyxl.load_workbook('./assets/prep_data.xlsx')
sheet = prep_data.active


# cells = sheet['B3':'D5']
i = 3
un = []; ip= []; js=[]
for _ in range(100):
    un1 = []; ip1 = []; js1 = []
    for c1, c2, c3 in sheet[f'B{i}':f'D{i+2}']:
        un1.append([c1.value, c2.value, c3.value])

    for c1, c2, c3 in sheet[f'E{i}':f'G{i+2}']:
        ip1.append([c1.value, c2.value, c3.value])

    for c1, c2, c3 in sheet[f'H{i}':f'J{i+2}']:
        js1.append([c1.value, c2.value, c3.value])
    
    un.append(un1)
    ip.append(ip1)
    js.append(js1)

    i+=5


In [3]:
un[1]

[[1, 1, 1], [2, 2.5, 3], [2, 2.5, 3]]

In [4]:
persons = []
for i in range(100):
    persons.append([un[i],ip[i],js[i]])

In [5]:
persons[0]

[[[1, 1, 1], [2, 2.5, 3], [2, 2.5, 3]],
 [[0.3333333333333333, 0.4, 0.5], [1, 1, 1], [0.3333, 0.4, 0.5]],
 [[0.3333, 0.4, 0.5], [2, 2.5, 3], [1, 1, 1]]]

In [6]:
persons_data = np.array(persons)

In [7]:
persons_data[0]
# har bir element bir odamning ma`lumotlarini ifodalaydi.
# person_data[0] -> birinchi odamning ma'lumotlari
# Ma'lumot 3 ta qismdan: 1) unloading capacity	2) Institutions and policies 3) Jumbo system



array([[[1.        , 1.        , 1.        ],
        [2.        , 2.5       , 3.        ],
        [2.        , 2.5       , 3.        ]],

       [[0.33333333, 0.4       , 0.5       ],
        [1.        , 1.        , 1.        ],
        [0.3333    , 0.4       , 0.5       ]],

       [[0.3333    , 0.4       , 0.5       ],
        [2.        , 2.5       , 3.        ],
        [1.        , 1.        , 1.        ]]])

In [8]:
persons_data[0][0] # unloading capacity

array([[1. , 1. , 1. ],
       [2. , 2.5, 3. ],
       [2. , 2.5, 3. ]])

In [9]:
persons_data[0][1] # Institutions and policies

array([[0.33333333, 0.4       , 0.5       ],
       [1.        , 1.        , 1.        ],
       [0.3333    , 0.4       , 0.5       ]])

In [10]:
persons_data[0][2] # Jumbo system

array([[0.3333, 0.4   , 0.5   ],
       [2.    , 2.5   , 3.    ],
       [1.    , 1.    , 1.    ]])

In [11]:
np.save('person_prep_data_3.npy', persons_data)

## Prepdata1

In [12]:
prep_data = openpyxl.load_workbook('./assets/prep_data1.xlsx')
sheet = prep_data.active


# cells = sheet['B3':'D5']
i = 3
un = []; ip= []; js=[]; dp = []
for _ in range(100):
    un1 = []; ip1 = []; js1 = []; dp1 = []
    for c1, c2, c3 in sheet[f'B{i}':f'D{i+3}']:
        un1.append([c1.value, c2.value, c3.value])

    for c1, c2, c3 in sheet[f'E{i}':f'G{i+3}']:
        ip1.append([c1.value, c2.value, c3.value])

    for c1, c2, c3 in sheet[f'H{i}':f'J{i+3}']:
        js1.append([c1.value, c2.value, c3.value])

    for c1, c2, c3 in sheet[f'K{i}':f'M{i+3}']:
        dp1.append([c1.value, c2.value, c3.value])
    
    un.append(un1)
    ip.append(ip1)
    js.append(js1)
    dp.append(dp1)

    i+=6

In [13]:
all_prep1_data = un+ip+js+dp

In [14]:
dp[0]

[[0.3333, 0.4, 0.5], [0.3333, 0.4, 0.5], [0.3333, 0.4, 0.5], [1, 1, 1]]

In [15]:
persons = []
for i in range(100):
    persons.append([un[i],ip[i],js[i],dp[i]])

In [16]:
persons[0]

[[[1, 1, 1], [2, 2.5, 3], [2, 2.5, 3], [2, 2.5, 3]],
 [[0.333333333333333, 0.4, 0.5], [1, 1, 1], [2, 2.5, 3], [2, 2.5, 3]],
 [[0.3333, 0.4, 0.5], [0.3333, 0.4, 0.5], [1, 1, 1], [2, 2.5, 3]],
 [[0.3333, 0.4, 0.5], [0.3333, 0.4, 0.5], [0.3333, 0.4, 0.5], [1, 1, 1]]]

In [17]:
persons_data = np.array(persons)

In [18]:
np.save('person_prep_data_1.npy',persons_data)

## Prepdata 2

In [19]:
prep_data = openpyxl.load_workbook('./assets/prep_data2.xlsx')
sheet = prep_data.active


# cells = sheet['B3':'D5']
i = 3
un = []; ip= []; js=[]
for _ in range(100):
    un1 = []; ip1 = []; js1 = []
    for c1, c2, c3 in sheet[f'B{i}':f'D{i+2}']:
        un1.append([c1.value, c2.value, c3.value])

    for c1, c2, c3 in sheet[f'E{i}':f'G{i+2}']:
        ip1.append([c1.value, c2.value, c3.value])

    for c1, c2, c3 in sheet[f'H{i}':f'J{i+2}']:
        js1.append([c1.value, c2.value, c3.value])

    
    un.append(un1)
    ip.append(ip1)
    js.append(js1)

    i+=5

In [20]:
all_prep2_data = un+ip+js

In [21]:
persons = []
for i in range(100):
    persons.append([un[i],ip[i],js[i]])

In [22]:
persons[0]

[[[1, 1, 1], [0.6666666666666666, 1, 2], [2, 2.5, 3]],
 [[0.5, 1, 1.5], [1, 1, 1], [2, 2.5, 3]],
 [[0.3333333333333333, 0.4, 0.5], [0.3333, 0.4, 0.5], [1, 1, 1]]]

In [23]:
persons_data = np.array(persons)

In [24]:
np.save('person_prep_data_2.npy',persons_data)

## Prepdata4

In [25]:
prep_data = openpyxl.load_workbook('./assets/prep_data4.xlsx')
sheet = prep_data.active


# cells = sheet['B3':'D5']
i = 3
un = []; ip= []; js=[]
for _ in range(100):
    un1 = []; ip1 = []; js1 = []
    for c1, c2, c3 in sheet[f'B{i}':f'D{i+2}']:
        un1.append([c1.value, c2.value, c3.value])

    for c1, c2, c3 in sheet[f'E{i}':f'G{i+2}']:
        ip1.append([c1.value, c2.value, c3.value])

    for c1, c2, c3 in sheet[f'H{i}':f'J{i+2}']:
        js1.append([c1.value, c2.value, c3.value])
    
    un.append(un1)
    ip.append(ip1)
    js.append(js1)

    i+=5


In [26]:
all_prep4_data = un+ip+js

In [27]:
persons = []
for i in range(100):
    persons.append([un[i],ip[i],js[i]])

In [28]:
persons_data = np.array(persons)

In [29]:
np.save('person_prep_data_4.npy',persons_data)

## Prepdata5

In [30]:
prep_data = openpyxl.load_workbook('./assets/prep_data5.xlsx')
sheet = prep_data.active


# cells = sheet['B3':'D5']
i = 3
un = []; ip= []; js=[]
for _ in range(100):
    un1 = []; ip1 = []; js1 = []
    for c1, c2, c3 in sheet[f'B{i}':f'D{i+2}']:
        un1.append([c1.value, c2.value, c3.value])

    for c1, c2, c3 in sheet[f'E{i}':f'G{i+2}']:
        ip1.append([c1.value, c2.value, c3.value])

    for c1, c2, c3 in sheet[f'H{i}':f'J{i+2}']:
        js1.append([c1.value, c2.value, c3.value])
    
    un.append(un1)
    ip.append(ip1)
    js.append(js1)

    i+=5

In [ ]:
all_prep5_data = un+ip+js

In [ ]:
persons = []
for i in range(100):
    persons.append([un[i],ip[i],js[i]])

In [ ]:
persons_data = np.array(persons)

In [ ]:
np.save('person_prep_data_5.npy',persons_data)